<x-layouts.portal title="Nouveau projet — Cerveau Projet">
<x-dg.shell current="projets" :identity="$identity" :is-administrator="$isAdministrator">
<div class="dg-page" style="max-width:1180px;margin-inline:auto">
<div style="display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:28px"><div><x-dg.label tone="night">Cerveau du Projet</x-dg.label><h1 class="dg-display dg-display--screen" style="margin-top:7px">{{ isset($intent)?($intent->title?:'Projet en préparation'):'Qu’est-ce que vous voulez réaliser ?' }}</h1><p style="max-width:720px">Pas de grand formulaire. Parlez simplement de votre idée. Le Cerveau la comprend et la structure progressivement avec vous.</p></div><x-dg.btn variant="quiet" :href="route('projects.index')">← Projets</x-dg.btn></div>
<div style="display:grid;grid-template-columns:minmax(0,1fr) 350px;gap:22px;align-items:start">
<section class="dg-card" style="min-height:560px;display:flex;flex-direction:column;padding:0;overflow:hidden"><div style="padding:18px 22px;border-bottom:1px solid #e7e2dc;display:flex;justify-content:space-between"><strong>Conversation</strong><span class="dg-meta">{{ isset($intent)?'Brouillon sauvegardé':'Projet zéro' }}</span></div><div style="padding:24px;display:flex;flex:1;flex-direction:column;gap:16px">
@if(isset($intent)) @foreach($intent->messages as $message)<div style="max-width:82%;align-self:{{ $message['role']==='user'?'flex-end':'flex-start' }};padding:13px 16px;border-radius:16px;background:{{ $message['role']==='user'?'#0d3b46':'#f4f0ea' }};color:{{ $message['role']==='user'?'#fff':'inherit' }};line-height:1.55">{{ $message['content'] }}</div>@endforeach @else <div style="max-width:82%;padding:14px 17px;border-radius:16px;background:#f4f0ea">Bonjour. Dites-moi votre idée avec vos propres mots. Même si elle n’est pas encore claire, on commence avec ça.</div>@endif
</div>
@if(!isset($intent)||$intent->status!=='CREATED')<form method="POST" action="{{ isset($intent)?route('projects.brain.start.reply',$intent):route('projects.brain.start.store') }}" style="padding:18px 22px;border-top:1px solid #e7e2dc">@csrf<div style="display:flex;gap:10px;align-items:flex-end"><textarea name="message" rows="3" required autofocus placeholder="Parlez au Cerveau comme à une personne…" style="flex:1;resize:vertical;border:1px solid #d9d3cc;border-radius:14px;padding:13px 15px;font:inherit">{{ old('message') }}</textarea><x-dg.btn variant="project" type="submit">Envoyer →</x-dg.btn></div>@error('message')<p style="color:#a33">{{ $message }}</p>@enderror</form>@endif</section>
<aside class="dg-card" style="display:flex;flex-direction:column;gap:15px"><x-dg.label tone="night">Projet vivant</x-dg.label>
@if(isset($intent)) @php($state=$intent->context['project_state']??[]) @php($zumraReference=$intent->context['zumra_group_reference']??null) @php($zumraChosen=$groups->firstWhere('public_reference',$zumraReference))<div><span class="dg-meta">État</span><div style="font-weight:700;margin-top:4px">{{ $intent->status==='CREATED'?'Créé':'En préparation' }}</div></div>
{{-- PROJET-ZUMRA-INVARIANT-001 — décision humaine explicite, jamais gérée par l'IA (project_state). --}}
<div style="padding:14px;border-radius:14px;background:{{ $zumraChosen?'#eef5f2':'#fff6ec' }}"><strong>ZUMRA d’ancrage</strong>
@if($zumraChosen)<p style="margin:7px 0 0;font-size:.9rem">« {{ $zumraChosen->name }} » — un projet appartient toujours à une ZUMRA, même porté par vous seul·e.</p>
@else<p style="margin:7px 0 10px;font-size:.9rem">Aucun projet ne naît sans ZUMRA — même porté par vous seul·e. Une ZUMRA peut commencer avec vous seul·e.</p>
@if($intent->status!=='CREATED') @if($groups->isNotEmpty())<form method="POST" action="{{ route('projects.brain.start.zumra.select',$intent) }}" style="display:flex;flex-direction:column;gap:7px;margin-bottom:10px">@csrf @foreach($groups as $group)<label class="dg-radio" style="padding:9px"><input type="radio" name="zumra_group_reference" value="{{ $group->public_reference }}" required>{{ $group->name }}</label>@endforeach<button type="submit" class="dg-btn dg-btn--quiet" style="align-self:flex-start">Choisir cette ZUMRA</button></form>@endif<x-dg.btn variant="project" :href="route('projects.brain.start.zumra.create',$intent)">Commencer ma ZUMRA maintenant →</x-dg.btn>@endif
@endif</div>
@foreach(['name'=>'Nom','activity'=>'Activité','goal'=>'Objectif','beneficiaries'=>'Bénéficiaires','location'=>'Lieu','mode'=>'Mode','existing_people_or_skills'=>'Personnes & compétences','existing_resources'=>'Ressources disponibles','identified_needs'=>'Besoins identifiés','constraints'=>'Contraintes'] as $key=>$label) @php($value=$state[$key]??null) @if((is_array($value)&&count($value))||(!is_array($value)&&filled($value)))<div><span class="dg-meta">{{ $label }}</span>@if(is_array($value))<div style="display:flex;flex-wrap:wrap;gap:6px;margin-top:7px">@foreach($value as $item)<span style="padding:5px 8px;border-radius:999px;background:#f4f0ea;font-size:.82rem">{{ $item }}</span>@endforeach</div>@else<p style="margin:5px 0 0">{{ $value }}</p>@endif</div>@endif @endforeach
@if($readyForConfirmation??false)<div style="padding:14px;border-radius:14px;background:#eef5f2"><strong>Prêt à devenir un vrai Projet</strong><p style="margin:7px 0 10px;font-size:.9rem">Le Cerveau a assez d’éléments. Vérifiez puis confirmez : aucune création n’a lieu avant ce clic.</p><details style="font-size:.86rem;margin-bottom:12px"><summary>Voir la structure préparée</summary><div style="margin-top:9px"><strong>{{ $candidate['name'] }}</strong><br>{{ $candidate['summary'] }}<br><br><b>Problème :</b> {{ $candidate['problem'] }}<br><b>Solution :</b> {{ $candidate['proposed_solution'] }}<br><b>Bénéficiaires :</b> {{ $candidate['beneficiaries'] }}</div></details><form method="POST" action="{{ route('projects.brain.start.confirm',$intent) }}">@csrf<x-dg.btn variant="project" type="submit">Créer ce projet →</x-dg.btn></form></div>@elseif($contentReady??false)<div style="padding:12px;border-radius:12px;background:#fff6ec;font-size:.88rem">Le Cerveau a fini de structurer votre idée. Il ne manque plus que la ZUMRA choisie ci-dessus pour pouvoir confirmer.</div>@else<div style="padding:12px;border-radius:12px;background:#fff6ec;font-size:.88rem">Le Cerveau continue à structurer. Aucun Projet canonique n’est créé sans confirmation explicite.</div>@endif
@else<p>Votre idée n’a pas besoin d’être structurée avant de commencer.</p>@endif</aside></div></div>
<style>@media(max-width:900px){.dg-page>div[style*="grid-template-columns"]{grid-template-columns:1fr!important}.dg-page aside{order:-1}}</style>
</x-dg.shell></x-layouts.portal>
