<x-layouts.portal title="Cerveau — {{ $project->name }} — DG Afrique">
<x-dg.shell current="projets" :identity="$identity" :is-administrator="$isAdministrator">
<style>
.brain-shell{display:grid;grid-template-columns:260px minmax(0,1fr) 330px;min-height:calc(100vh - 110px);border:1px solid var(--dg-line);border-radius:18px;overflow:hidden;background:#fff}.brain-side{background:#f7f8f4;border-right:1px solid var(--dg-line);padding:18px}.brain-right{border-left:1px solid var(--dg-line);padding:18px;background:#fbfbf8}.brain-main{display:flex;flex-direction:column;min-height:720px}.brain-project{display:block;padding:11px 12px;border-radius:12px;color:var(--dg-text);text-decoration:none;margin:3px 0}.brain-project.active{background:#e9efe7;color:var(--dg-forest);font-weight:700}.brain-head{padding:20px 24px;border-bottom:1px solid var(--dg-line);display:flex;justify-content:space-between;align-items:center}.brain-thread{padding:26px;display:flex;flex-direction:column;gap:16px;flex:1;overflow:auto}.brain-msg{max-width:78%;padding:13px 15px;border-radius:16px;line-height:1.55;font-size:14px}.brain-msg.user{align-self:flex-end;background:var(--dg-forest);color:#fff}.brain-msg.assistant,.brain-msg.system{align-self:flex-start;background:#f0f2ed}.brain-draft{align-self:flex-start;max-width:88%;border:1px solid #d9dfd3;border-radius:16px;padding:16px;background:#fff;box-shadow:0 8px 24px rgba(26,50,35,.06)}.brain-draft dl{display:grid;grid-template-columns:100px 1fr;gap:7px 12px;font-size:13px}.brain-compose{padding:18px 22px;border-top:1px solid var(--dg-line)}.brain-compose textarea{width:100%;min-height:82px;border:1px solid var(--dg-line);border-radius:14px;padding:13px}.brain-card{border:1px solid var(--dg-line);border-radius:14px;padding:14px;margin-top:10px}.brain-kicker{text-transform:uppercase;letter-spacing:.09em;font-size:11px;font-weight:800;color:#758077}.brain-empty{color:#788078;font-size:13px;line-height:1.5}@media(max-width:1100px){.brain-shell{grid-template-columns:210px minmax(0,1fr)}.brain-right{display:none}}@media(max-width:760px){.brain-shell{display:block}.brain-side{display:none}.brain-msg,.brain-draft{max-width:94%}}
</style>
<div class="dg-page" style="max-width:none;padding-left:18px;padding-right:18px">
@if(session('status'))<div class="dg-band" style="margin-bottom:12px">{{ session('status') }}</div>@endif
@if($errors->any())<div class="dg-band" style="margin-bottom:12px">{{ $errors->first() }}</div>@endif
<div class="brain-shell">
<aside class="brain-side"><div class="brain-kicker">Mes projets</div><h2 style="font-size:20px">Projet V2</h2>@foreach($visibleProjects as $candidate)<a class="brain-project {{ $candidate->id === $project->id ? 'active':'' }}" href="{{ route('projects.brain.show',$candidate) }}"><div>{{ $candidate->name }}</div><small>{{ str_replace('_',' ',mb_strtolower($candidate->status)) }}</small></a>@endforeach<a href="{{ route('projects.index') }}" class="brain-project">← Vue classique</a></aside>
<main class="brain-main"><header class="brain-head"><div><div class="brain-kicker">Cerveau permanent du projet</div><h1 style="font-size:22px;margin:3px 0">{{ $project->name }}</h1></div><a href="{{ route('projects.show',$project) }}" class="dg-btn dg-btn--secondary">Fiche projet</a></header>
<section class="brain-thread">@if($messages->isEmpty())<div class="brain-msg assistant">Bonjour. Parlons du projet naturellement. Je peux réfléchir avec vous et, lorsqu’un manque devient assez clair, vous proposer un Besoin à confirmer. Je n’écris jamais dans le Core sans votre accord.</div>@endif
@foreach($messages as $message)<div class="brain-msg {{ mb_strtolower($message->role) }}">{{ $message->content }}</div>@if(($message->meta['draft_reference']??null)&&($draft=$drafts->get($message->meta['draft_reference']))) @php($p=$draft->payload)<div class="brain-draft"><div class="brain-kicker">Action proposée — aucune mutation</div><h3>{{ $p['title'] }}</h3><p class="brain-empty">{{ $p['context'] }}</p><dl><dt>Catégorie</dt><dd>{{ $needConfiguration['categories'][$p['category']]??$p['category'] }}</dd><dt>Lieu</dt><dd>{{ $p['location']??'Non précisé' }}</dd><dt>Mode</dt><dd>{{ $p['collaboration_mode'] }}</dd></dl><form method="POST" action="{{ route('projects.brain.needs.confirm',[$project,$draft]) }}" style="display:inline">@csrf<button class="dg-btn">Créer ce besoin</button></form> <form method="POST" action="{{ route('projects.brain.drafts.cancel',[$project,$draft]) }}" style="display:inline">@csrf<button class="dg-btn dg-btn--secondary">Pas maintenant</button></form></div>@endif @endforeach</section>
<form class="brain-compose" method="POST" action="{{ route('projects.brain.needs.prepare',$project) }}">@csrf<textarea name="message" required minlength="2" maxlength="3000" placeholder="Parlez au Cerveau comme à une personne…">{{ old('message') }}</textarea><div style="display:flex;justify-content:space-between;align-items:center;margin-top:8px"><span class="brain-empty">Conversation permanente · toute action Core exige votre confirmation</span><button class="dg-btn" type="submit">Envoyer →</button></div></form></main>
<aside class="brain-right"><div class="brain-kicker">État réel du Core</div><h3>Aujourd’hui</h3><div class="brain-card"><div class="brain-kicker">Projet</div><h4>{{ $project->name }}</h4><div class="brain-empty">{{ str_replace('_',' ',mb_strtolower($project->status)) }}</div></div><div style="margin-top:22px;display:flex;justify-content:space-between"><div class="brain-kicker">Besoins actifs</div><strong>{{ $projectNeeds->count() }}</strong></div>@forelse($projectNeeds as $need)<a href="{{ route('needs.show',$need) }}" class="brain-card" style="display:block;text-decoration:none;color:inherit"><h4>{{ $need->title }}</h4><div class="brain-empty">{{ $needConfiguration['categories'][$need->category]??$need->category }} · {{ str_replace('_',' ',mb_strtolower($need->status)) }}</div></a>@empty<p class="brain-empty">Aucun besoin actif. Le Cerveau peut en proposer un lorsque la conversation révèle un manque réel.</p>@endforelse</aside>
</div></div></x-dg.shell></x-layouts.portal>
