<style>
.accompaniment-page{min-height:100vh;padding:clamp(1rem,3vw,3rem);background:linear-gradient(180deg,#f6fbfd 0,#f4f8fb 36rem)}
.accompaniment-shell{width:min(76rem,100%);margin:0 auto}.accompaniment-nav{display:flex;justify-content:space-between;gap:1rem;margin-bottom:1.2rem}.accompaniment-nav a{color:var(--ocean);font-size:.78rem;font-weight:800;text-decoration:none}
.accompaniment-hero{display:grid;grid-template-columns:minmax(0,1fr) 17rem;gap:2rem;border:1px solid var(--line);border-radius:1.35rem;padding:clamp(1.5rem,4vw,3rem);background:#fff}.accompaniment-hero h1{margin:.25rem 0 .8rem;color:var(--navy);font-size:clamp(2rem,4vw,3.7rem);line-height:1.02}.accompaniment-hero>div>p:last-child{color:var(--muted);line-height:1.65}.accompaniment-hero aside{display:grid;align-self:start;gap:.45rem;border-radius:1rem;padding:1.2rem;background:var(--navy);color:#fff}.accompaniment-hero aside span,.accompaniment-hero aside small{color:#9fb1c2;font-size:.68rem}
.accompaniment-boundary,.accompaniment-start,.accompaniment-active,.accompaniment-types,.accompaniment-timeline,.admin-accompaniment-list{margin-top:1rem;border:1px solid var(--line);border-radius:1rem;padding:1.4rem;background:#fff}.accompaniment-boundary{border-color:#b9ead4;background:#ebfaf3}.accompaniment-boundary strong{color:#14744b}.accompaniment-boundary p,.accompaniment-start p,.accompaniment-active p{color:var(--muted);font-size:.8rem;line-height:1.55}
.accompaniment-start,.accompaniment-active{display:grid;grid-template-columns:minmax(0,1fr) 16rem;align-items:center;gap:2rem}.accompaniment-start h2,.accompaniment-active h2,.accompaniment-types h2,.section-heading h2{margin:0;color:var(--navy)}.accompaniment-types>div{display:flex;flex-wrap:wrap;gap:.5rem;margin-top:.9rem}.accompaniment-types span{border-radius:999px;padding:.45rem .7rem;color:#17618f;background:#eaf5fb;font-size:.7rem;font-weight:750}
.section-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:1rem}.section-heading small{color:var(--muted);font-size:.72rem}.accompaniment-timeline>article{display:grid;grid-template-columns:1rem 1fr;gap:1rem;padding:1.35rem 0;border-bottom:1px solid var(--line)}.timeline-mark{width:.65rem;height:.65rem;margin-top:.25rem;border-radius:50%;background:var(--cyan)}.timeline-meta{display:flex;flex-wrap:wrap;gap:.5rem}.timeline-meta strong{color:var(--ocean);font-size:.72rem}.timeline-meta span,.timeline-meta time{color:var(--muted);font-size:.67rem}.accompaniment-timeline h3{margin:.35rem 0;color:var(--navy);font-size:.95rem}.accompaniment-timeline article p{font-size:.8rem;line-height:1.6}.accompaniment-timeline article aside{display:flex;gap:.55rem;margin-top:.75rem;border-left:3px solid var(--amber);padding:.5rem .7rem;background:#fff9ea;font-size:.72rem}
.accompaniment-empty{border:1px dashed #c9d5df;border-radius:.85rem;padding:1.2rem;color:var(--muted);background:#fafcfd}.admin-accompaniment-card{margin-top:1rem;border:1px solid var(--line);border-radius:1rem;padding:1.2rem;background:#fafcfd}.admin-accompaniment-card>header{display:flex;justify-content:space-between;gap:1rem}.admin-accompaniment-card h3{margin:.25rem 0;color:var(--navy)}.admin-accompaniment-card header span,.admin-accompaniment-card header p{color:var(--muted);font-size:.7rem}
.accompaniment-action-form{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.8rem;margin-top:1rem}.accompaniment-action-form label{display:grid;gap:.35rem;color:var(--navy);font-size:.72rem;font-weight:750}.accompaniment-action-form input,.accompaniment-action-form select,.accompaniment-action-form textarea{width:100%;border:1px solid var(--line);border-radius:.7rem;padding:.7rem;background:#fff;font:inherit}.accompaniment-action-form textarea{min-height:6rem}.accompaniment-action-form .wide{grid-column:1/-1}
@media(max-width:850px){.accompaniment-hero,.accompaniment-start,.accompaniment-active{grid-template-columns:1fr}.accompaniment-action-form{grid-template-columns:1fr}.accompaniment-action-form .wide{grid-column:auto}.admin-accompaniment-card>header{flex-direction:column}}
</style>
