<x-layouts.portal title="Administration — DG Afrique">
    <main class="admin-content">
        <div class="admin-heading"><div><p class="eyebrow dark">Administration DG Afrique</p><h1>Configurer le profil de capacités</h1><p>Ces modifications s’appliquent au formulaire membre sans déploiement.</p></div><a href="{{ route('member.space') }}">Retour à Mon espace</a></div>
        @if (session('status'))<div class="alert success">{{ session('status') }}</div>@endif @if ($errors->any())<div class="alert danger">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ route('administration.profile.update') }}" class="admin-form">@csrf @method('PUT')
            <section><h2>Présentation</h2><label>Titre<input name="title" value="{{ old('title', $configuration['title']) }}" required></label><label>Introduction<textarea name="introduction" rows="3" required>{{ old('introduction', $configuration['introduction']) }}</textarea></label></section>
            <section><h2>Sections et ordre</h2><div class="admin-sections">@foreach($configuration['sections'] as $key => $section)<article><label class="check-row"><input type="checkbox" name="sections[{{ $key }}][enabled]" value="1" @checked(old("sections.$key.enabled", $section['enabled']))> Section active</label><label>Ordre<input type="number" name="sections[{{ $key }}][order]" min="1" max="999" value="{{ old("sections.$key.order", $section['order']) }}" required></label><label>Titre<input name="sections[{{ $key }}][title]" value="{{ old("sections.$key.title", $section['title']) }}" required></label><label>Texte d’aide<textarea name="sections[{{ $key }}][help]" rows="2">{{ old("sections.$key.help", $section['help']) }}</textarea></label></article>@endforeach</div></section>
            <section><h2>Référentiels proposés</h2><label>Modes de participation — CODE|Libellé<textarea name="participation_modes_text" rows="5">{{ old('participation_modes_text', collect($configuration['participation_modes'])->map(fn($mode) => $mode['value'].'|'.$mode['label'])->implode("\n")) }}</textarea></label><label>Pays suggérés — codes à deux lettres<textarea name="country_suggestions_text" rows="3">{{ old('country_suggestions_text', implode("\n", $configuration['country_suggestions'])) }}</textarea></label></section>
            <section><h2>Libellés et champs obligatoires</h2><div class="admin-sections">@foreach($configuration['field_labels'] as $key => $label)<article><label>{{ $key }}<input name="field_labels[{{ $key }}]" value="{{ old("field_labels.$key", $label) }}" required></label>@if(array_key_exists($key, $configuration['required_fields']))<label class="check-row"><input type="checkbox" name="required_fields[{{ $key }}]" value="1" @checked(old("required_fields.$key", $configuration['required_fields'][$key]))> Champ obligatoire</label>@endif</article>@endforeach</div><label>Texte du bouton<input name="submit_label" value="{{ old('submit_label', $configuration['submit_label']) }}" required></label><label>Notice sans score<input name="no_score_notice" value="{{ old('no_score_notice', $configuration['no_score_notice']) }}" required></label></section>
            <section><h2>Consentement d’orientation</h2><label>Libellé<input name="orientation_consent_label" value="{{ old('orientation_consent_label', $configuration['orientation_consent_label']) }}" required></label><label>Explication<textarea name="orientation_consent_help" rows="3" required>{{ old('orientation_consent_help', $configuration['orientation_consent_help']) }}</textarea></label></section>
            <button class="primary-button" type="submit">Enregistrer la configuration</button>
        </form>
    </main>
</x-layouts.portal>
