<x-layouts.admin title="Administration des recommandations — DG Afrique" current="engines">
    <main class="admin-content">
        <div class="admin-heading"><div><p class="eyebrow dark">Administration DG Afrique</p><h1>Configurer les recommandations</h1><p>Les règles activables déterminent les rapprochements permis, jamais une valeur humaine.</p></div><div class="admin-links"><a href="{{ route('administration.discovery.edit') }}">Découverte</a><a href="{{ route('recommendations.index') }}">Voir les recommandations</a><a href="{{ route('member.space') }}">Mon espace</a></div></div>
        @if(session('status'))<div class="alert success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert danger">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ route('administration.recommendations.update') }}" class="admin-form">@csrf @method('PUT')
            <section><h2>Présentation</h2><label>Titre<input name="title" value="{{ old('title', $configuration['title']) }}" required></label><label>Introduction<textarea name="introduction" rows="3" required>{{ old('introduction', $configuration['introduction']) }}</textarea></label><label>Notice de prudence<textarea name="privacy_notice" rows="3" required>{{ old('privacy_notice', $configuration['privacy_notice']) }}</textarea></label></section>
            <section><h2>État vide et actions</h2><label>Titre vide<input name="empty_title" value="{{ old('empty_title', $configuration['empty_title']) }}" required></label><label>Explication vide<textarea name="empty_text" rows="3" required>{{ old('empty_text', $configuration['empty_text']) }}</textarea></label><label>Libellé du détail<input name="detail_button" value="{{ old('detail_button', $configuration['detail_button']) }}" required></label><label>Libellé pour masquer<input name="hide_button" value="{{ old('hide_button', $configuration['hide_button']) }}" required></label></section>
            <section><h2>Bornes du moteur</h2><div class="admin-sections"><article><label>Résultats maximum<input type="number" name="max_results" min="3" max="24" value="{{ old('max_results', $configuration['max_results']) }}" required></label></article><article><label>Profils examinés<input type="number" name="candidate_pool" min="20" max="500" value="{{ old('candidate_pool', $configuration['candidate_pool']) }}" required></label></article><article><label>Raisons maximum<input type="number" name="max_reasons" min="1" max="8" value="{{ old('max_reasons', $configuration['max_reasons']) }}" required></label></article></div></section>
            <section><h2>Règles activables</h2><div class="admin-sections"><article><label class="check-row"><input type="checkbox" name="learning_transmission" value="1" @checked(old('learning_transmission', $configuration['learning_transmission']))> Apprentissage ↔ transmission</label></article><article><label class="check-row"><input type="checkbox" name="transmission_learning" value="1" @checked(old('transmission_learning', $configuration['transmission_learning']))> Transmission ↔ apprentissage</label></article><article><label class="check-row"><input type="checkbox" name="shared_capability" value="1" @checked(old('shared_capability', $configuration['shared_capability']))> Capacité partagée</label></article><article><label class="check-row"><input type="checkbox" name="shared_domain" value="1" @checked(old('shared_domain', $configuration['shared_domain']))> Domaine commun</label></article><article><label class="check-row"><input type="checkbox" name="location_context" value="1" @checked(old('location_context', $configuration['location_context']))> Contexte de localisation</label></article><article><label class="check-row"><input type="checkbox" name="participation_context" value="1" @checked(old('participation_context', $configuration['participation_context']))> Mode de participation</label></article></div></section>
            <button class="primary-button" type="submit">Enregistrer la configuration</button>
        </form>
    </main>
</x-layouts.admin>
