<?php
declare(strict_types=1);
namespace App\Application\Projects;
use App\Application\Needs\NeedService; use App\Application\Zumra\ZumraGroupService; use App\Models\Need; use App\Models\Project; use App\Models\ProjectEvent; use App\Models\ZumraGroup; use App\Models\ZumraGroupMembership; use App\Models\ZumraProgramMembership; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str;
final class ProjectService
{
    public function __construct(private readonly ZumraGroupService $groups,private readonly NeedService $needs){}
    public function create(string $actor,array $data,array $config): Project
    {
        abort_unless(ZumraProgramMembership::query()->where('core_identity_reference',$actor)->where('status',ZumraProgramMembership::STATUS_ACTIVE)->exists(),403);
        $owner=$actor; $status=Project::STATUS_PROPOSED;
        if($data['owner_type']===Project::OWNER_GROUP){$group=ZumraGroup::query()->where('public_reference',$data['group_reference'])->firstOrFail(); abort_unless($this->activeGroupMember($group->id,$actor),403); abort_unless(in_array($data['property_regime'],['ZUMRA_COLLECTIVE','PARTNERSHIP','COMMUNITY_INTEREST'],true),422,'Le régime choisi ne correspond pas au porteur collectif.'); $owner=$group->id;}
        else { abort_unless(in_array($data['property_regime'],['PERSONAL_SUPPORTED','PARTNERSHIP','COMMUNITY_INTEREST'],true),422,'Le régime choisi ne correspond pas au porteur personnel.'); }
        $limit=$data['owner_type']===Project::OWNER_PERSON?(int)$config['max_active_personal_projects']:(int)$config['max_active_group_projects']; abort_if(Project::query()->where('owner_type',$data['owner_type'])->where('owner_reference',$owner)->whereNotIn('status',[Project::STATUS_COMPLETED,Project::STATUS_ARCHIVED])->count()>=$limit,409,'Le nombre maximal de projets actifs est atteint.');
        $source=null; if(!empty($data['source_need_reference'])){$need=Need::query()->where('public_reference',$data['source_need_reference'])->firstOrFail(); abort_unless($this->needs->canView($need,$actor),404); $source=$need->id;}
        return DB::transaction(function()use($actor,$data,$owner,$status,$source):Project{$project=Project::query()->create(['public_reference'=>(string)Str::uuid(),'owner_type'=>$data['owner_type'],'owner_reference'=>$owner,'initiator_core_reference'=>$actor,'source_need_id'=>$source,'name'=>$data['name'],'summary'=>$data['summary'],'problem'=>$data['problem'],'proposed_solution'=>$data['proposed_solution'],'beneficiaries'=>$data['beneficiaries'],'domain'=>$data['domain'],'participation_mode'=>$data['participation_mode'],'location'=>$data['location']??null,'objectives'=>ProjectList::fromText($data['objectives']),'required_capabilities'=>ProjectList::fromText($data['required_capabilities']),'required_resources'=>ProjectList::fromText($data['required_resources']),'risks'=>ProjectList::fromText($data['risks']),'property_regime'=>$data['property_regime'],'visibility'=>$data['owner_type']===Project::OWNER_PERSON&&$data['visibility']===Project::VISIBILITY_GROUP?Project::VISIBILITY_PRIVATE:$data['visibility'],'status'=>$status,'maturity'=>'IDEA','decided_by_core_reference'=>$status===Project::STATUS_ADOPTED?$actor:null,'adopted_at'=>$status===Project::STATUS_ADOPTED?now():null]); foreach(ProjectList::fromText($data['milestones'],12) as $i=>$title){$project->milestones()->create(['title'=>$title,'position'=>$i+1]);}$this->event($project,$status===Project::STATUS_ADOPTED?'PROJECT_ADOPTED':'PROJECT_PROPOSED',$actor);return $project;});
    }
    public function transition(Project $project,string $actor,string $status,?string $maturity=null):void{$this->assertDecision($project,$actor);$allowed=match($status){Project::STATUS_ADOPTED=>[Project::STATUS_PROPOSED],Project::STATUS_IN_PROGRESS=>[Project::STATUS_PROPOSED,Project::STATUS_ADOPTED],Project::STATUS_COMPLETED=>[Project::STATUS_IN_PROGRESS],Project::STATUS_ARCHIVED=>[Project::STATUS_PROPOSED,Project::STATUS_ADOPTED,Project::STATUS_IN_PROGRESS,Project::STATUS_COMPLETED],default=>[]};abort_unless(in_array($project->status,$allowed,true),409);if($project->owner_type===Project::OWNER_GROUP&&$status===Project::STATUS_IN_PROGRESS)abort_unless(in_array($project->status,[Project::STATUS_ADOPTED],true),409,'Une ZUMRA doit adopter le projet avant son démarrage.');$project->update(['status'=>$status,'maturity'=>$maturity?:$project->maturity,'decided_by_core_reference'=>$actor,'adopted_at'=>$status===Project::STATUS_ADOPTED?now():$project->adopted_at,'started_at'=>$status===Project::STATUS_IN_PROGRESS?now():$project->started_at,'completed_at'=>$status===Project::STATUS_COMPLETED?now():$project->completed_at,'archived_at'=>$status===Project::STATUS_ARCHIVED?now():null]);$this->event($project,'PROJECT_'.$status,$actor);}
    public function canView(Project $p,string $actor):bool{if($p->initiator_core_reference===$actor||($p->owner_type===Project::OWNER_PERSON&&$p->owner_reference===$actor))return true;if($p->owner_type===Project::OWNER_GROUP&&$this->activeGroupMember($p->owner_reference,$actor))return true;if($p->status===Project::STATUS_ARCHIVED||$p->visibility===Project::VISIBILITY_PRIVATE)return false;if($p->visibility===Project::VISIBILITY_PUBLIC)return true;if($p->visibility===Project::VISIBILITY_PROGRAM)return ZumraProgramMembership::query()->where('core_identity_reference',$actor)->where('status',ZumraProgramMembership::STATUS_ACTIVE)->exists();return false;}
    public function canDecide(Project $p,string $actor):bool{if($p->owner_type===Project::OWNER_PERSON)return hash_equals($p->owner_reference,$actor);$group=ZumraGroup::query()->find($p->owner_reference);return $group&&$this->groups->isLeader($group,$actor);}
    private function assertDecision(Project $p,string $a):void{abort_unless($this->canDecide($p,$a),403);} private function activeGroupMember(string $g,string $a):bool{return ZumraGroupMembership::query()->where('zumra_group_id',$g)->where('core_identity_reference',$a)->where('status',ZumraGroupMembership::STATUS_ACTIVE)->exists();} private function event(Project $p,string $e,string $a):void{ProjectEvent::query()->create(['project_id'=>$p->id,'event'=>$e,'actor_core_reference'=>$a,'context'=>[],'occurred_at'=>now()]);}
}
