<x-layouts.portal title="{{ $group->name }} — ZUMRA">
    <div class="group-page">
        <header class="membership-topbar"><a href="{{ route('zumra.groups.index') }}">← Les ZUMRA</a><strong><i>Z</i> {{ $group->name }}</strong><a href="{{ route('zumra.index') }}">Fil ZUMRA</a></header>
        <main class="group-detail-content">
            @if(session('status'))<div class="alert success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert danger">{{ $errors->first() }}</div>@endif
            <section class="group-detail-hero"><div class="group-monogram">{{ mb_strtoupper(mb_substr($group->name,0,1)) }}</div><div><p class="eyebrow">{{ $group->domain }}</p><h1>{{ $group->name }}</h1><p>{{ $group->founding_objective }}</p><div><span>{{ match($group->participation_mode){'PHYSICAL'=>'Physique','DIGITAL'=>'Numérique',default=>'Hybride'} }}</span><span>{{ $group->active_member_count }} membre{{ $group->active_member_count > 1 ? 's' : '' }}</span><span>{{ $group->maturity === 'ESTABLISHED' ? 'ZUMRA établie' : 'ZUMRA émergente' }}</span></div></div><aside><small>ÉTAT OPÉRATIONNEL</small><strong>{{ match($group->state){'CONSTITUTING'=>'En constitution','READY'=>'Prête à valider','VALIDATED'=>'Validée','ACTIVE'=>'Active','WARNED'=>'Avertie','SUSPENDED'=>'Suspendue','REHABILITATING'=>'En réhabilitation',default=>$group->state} }}</strong><span>{{ $roles->where('status','ACCEPTED')->count() }}/5 responsabilités acceptées</span></aside></section>
            <div class="group-detail-grid"><div>
                <section class="group-panel"><div class="group-panel-heading"><div><small>GOUVERNANCE FONDATRICE</small><h2>Cinq responsabilités, cinq personnes.</h2></div><span>{{ $roles->where('status','ACCEPTED')->count() === 5 ? 'Gouvernance complète' : 'Constitution en cours' }}</span></div><div class="founder-role-grid">@foreach($roles as $role) @php($profile=$roleProfiles->get($role->core_identity_reference))<article class="{{ strtolower($role->status) }}"><i>{{ $loop->iteration }}</i><div><small>{{ $role->status === 'ACCEPTED' ? 'RESPONSABILITÉ ACCEPTÉE' : 'SIÈGE VACANT' }}</small><h3>{{ \App\Models\ZumraGroupRole::LABELS[$role->role] }}</h3><p>{{ $profile?->discovery_display_name ?: ($role->status === 'ACCEPTED' ? 'Membre attesté' : 'Aucune personne nommée') }}</p></div></article>@endforeach</div><p class="group-integrity">Le système ne complète jamais les sièges avec des profils fictifs et ne nomme personne par matching.</p></section>
                <section class="group-panel collective-capability-panel"><div class="group-panel-heading"><div><small>CAPACITÉ COLLECTIVE</small><h2>{{ $collectiveCapabilitySettings['section_title'] }}</h2></div><span>{{ $collectiveCapabilities->count() }} force{{ $collectiveCapabilities->count() > 1 ? 's' : '' }} mobilisable{{ $collectiveCapabilities->count() > 1 ? 's' : '' }}</span></div><p class="collective-capability-intro">{{ $collectiveCapabilitySettings['section_intro'] }}</p>@if($collectiveCapabilities->isEmpty())<div class="collective-capability-empty">{{ $collectiveCapabilitySettings['empty_text'] }}</div>@else<div class="collective-capability-grid">@foreach($collectiveCapabilities as $capability)<article><i>{{ mb_strtoupper(mb_substr($capability->label,0,1)) }}</i><div><h3>{{ $capability->label }}</h3><p>{{ $capability->member_count }} membre{{ $capability->member_count > 1 ? 's' : '' }} volontaire{{ $capability->member_count > 1 ? 's' : '' }} et mobilisable{{ $capability->member_count > 1 ? 's' : '' }}</p></div></article>@endforeach</div>@endif<p class="group-integrity">Le profil collectif agrège des capacités consenties. Il ne remplace pas les personnes et n’affiche aucune identité privée.</p></section>
                <section class="group-panel"><small>CHARTE INTERNE</small><h2>Les règles de cette équipe</h2><div class="group-charter">{!! nl2br(e($group->internal_charter)) !!}</div></section>
            </div><aside class="group-actions-panel">
                <section><small>VOTRE RELATION</small><h2>{{ !$membership ? 'Vous ne faites pas encore partie de cette ZUMRA.' : match($membership->status){'ACTIVE'=>'Vous êtes membre','INVITED'=>'Vous êtes invité','REQUESTED'=>'Votre demande est étudiée','LEFT'=>'Vous avez quitté cette ZUMRA',default=>$membership->status} }}</h2>
                    @if(!$membership || in_array($membership->status,['LEFT','EXCLUDED']))<form method="POST" action="{{ route('zumra.groups.request',$group) }}">@csrf<label>Pourquoi souhaitez-vous rejoindre cette équipe ?<textarea name="motivation" rows="4" maxlength="800"></textarea></label><button type="submit">Envoyer ma demande</button></form>
                    @elseif($membership->status==='INVITED')<form method="POST" action="{{ route('messages.invitation',$group) }}">@csrf<button type="submit">Échanger avant d’accepter</button></form><form method="POST" action="{{ route('zumra.groups.invitation.accept',$group) }}">@csrf<button type="submit">Accepter l’invitation</button></form>
                    @elseif($membership->status==='REQUESTED')<p>Attendez l’approbation d’un responsable. Une demande ne donne aucun droit de membre.</p>
                    @elseif($membership->status==='ACTIVE')<form method="POST" action="{{ route('messages.zumra',$group) }}">@csrf<button type="submit">Ouvrir la conversation ZUMRA</button></form>@if(!$isLeader)<form method="POST" action="{{ route('zumra.groups.leave',$group) }}">@csrf<button class="quiet" type="submit">Quitter librement la ZUMRA</button></form>@endif @endif
                    @if($group->state !== \App\Models\ZumraGroup::STATE_SUSPENDED)<a href="{{ route('comments.zumra-activity',$group) }}" style="display:block;margin-top:.8rem;text-align:center;color:var(--ocean);font-size:.68rem;font-weight:900;text-decoration:none">Contribuer à l’activité →</a>@endif
                </section>
                @if($membership?->status === 'ACTIVE')<section class="collective-consent"><small>MES CAPACITÉS DANS CETTE ZUMRA</small><h2>Un choix volontaire, réversible.</h2><p>Seules vos capacités déjà découvrables peuvent être comptées. Votre nom ne figure jamais dans l’agrégat.</p><form method="POST" action="{{ route('zumra.groups.collective-capabilities.consent',$group) }}">@csrf @method('PUT')<label><input type="checkbox" name="collective_capability_consent" value="1" @checked($membership->collective_capability_consent)><span>{{ $collectiveCapabilitySettings['consent_label'] }}</span></label><button type="submit">Enregistrer mon choix</button></form></section>@endif
                @if($isLeader)<section><small>ESPACE RESPONSABLE</small><h2>Inviter un adhérent</h2><p>Utilisez la référence publique visible sur son profil. L’invitation devra être acceptée.</p><form method="POST" action="{{ route('zumra.groups.invite',$group) }}">@csrf<label>Référence publique<input name="person_reference" placeholder="xxxxxxxx-xxxx-…" required></label><button type="submit">Envoyer l’invitation</button></form></section>
                @if($pendingRequests->isNotEmpty())<section><small>DEMANDES EN ATTENTE</small>@foreach($pendingRequests as $pending)<article class="group-request"><strong>{{ $requestProfiles->get($pending->core_identity_reference)?->discovery_display_name ?: 'Adhérent ZUMRA' }}</strong><p>{{ $pending->motivation ?: 'Aucune motivation renseignée.' }}</p><form method="POST" action="{{ route('zumra.groups.requests.approve',[$group,$pending->id]) }}">@csrf<button type="submit">Approuver</button></form></article>@endforeach</section>@endif
                @endif
            </aside></div>
        </main>
    </div>
</x-layouts.portal>
