<x-layouts.member :title="$group->name" active="zumra"><div class="dg-space"><a class="dg-space-text-link" href="{{ route('zumra.index') }}">← Les ZUMRA</a><p class="dg-space-eyebrow">FORMATION · TRAVAIL · ADORATION</p><h1>{{ $group->name }}</h1><p class="dg-space-description">{{ $group->founding_objective }}</p>
@if ($collectivePriority)<section class="dg-space-priority"><p>{{ $collectivePriority['label'] }}</p><h2>{{ $collectivePriority['heading'] }}</h2><p>{{ $collectivePriority['body'] }}</p><x-dg.button :href="$collectivePriority['primary']['href']" variant="solar">{{ $collectivePriority['primary']['label'] }}</x-dg.button></section>@endif
@if ($myPendingRoleProposal)<section class="dg-space-section"><h2>Une responsabilité vous est proposée.</h2><p>{{ \App\Models\ZumraGroupRole::LABELS[$myPendingRoleProposal->role] }}</p><p>Accepter reste entièrement votre choix.</p><form method="POST" action="{{ route('zumra.groups.roles.accept', [$group, $myPendingRoleProposal->role]) }}">@csrf<x-dg.button type="submit">Accepter cette responsabilité</x-dg.button></form></section>@endif
<section class="dg-space-section"><h2>Votre place dans la communauté</h2>
@if ($membership?->status === 'ACTIVE')<p>Vous êtes membre de cette ZUMRA.</p>
@elseif ($membership?->status === 'REQUESTED')<p>Votre demande est en cours d’examen.</p>
@elseif ($membership?->status === 'INVITED')<p>Vous avez reçu une invitation.</p><form method="POST" action="{{ route('zumra.groups.invitation.accept', $group) }}">@csrf<x-dg.button type="submit">Accepter l’invitation</x-dg.button></form>
@else<p>Vous pouvez demander à rejoindre cette communauté. Ses règles d’accueil s’appliquent.</p><form method="POST" action="{{ route('zumra.groups.request', $group) }}">@csrf<x-dg.button type="submit">Demander à rejoindre</x-dg.button></form>@endif
</section>
@if ($isLeader)<section id="demandes" class="dg-space-section"><h2>Demandes à examiner</h2>@forelse ($pendingRequests as $requestMembership)<article class="dg-space-section"><h3>Une personne souhaite vous rejoindre</h3><form method="POST" action="{{ route('zumra.groups.requests.approve', [$group, $requestMembership]) }}">@csrf<x-dg.button type="submit">Accepter cette demande</x-dg.button></form></article>@empty<p>Aucune demande en attente.</p>@endforelse</section>@endif
<section class="dg-space-section"><h2>Nos projets</h2>@forelse ($groupProjects as $project)<a class="dg-space-row" href="{{ route('projects.show', $project) }}"><strong>{{ $project->name }}</strong><span aria-hidden="true">→</span></a>@empty<p>Aucun projet accessible à afficher.</p>@endforelse</section>
<section class="dg-space-section"><h2>Nos besoins</h2>@forelse ($groupNeeds as $need)<a class="dg-space-row" href="{{ route('needs.show', $need) }}"><strong>{{ $need->title }}</strong><span aria-hidden="true">→</span></a>@empty<p>Aucun besoin accessible à afficher.</p>@endforelse</section>
<section class="dg-space-section"><h2>Nos missions</h2>@forelse ($groupMissions as $mission)<a class="dg-space-row" href="{{ route('missions.show', $mission) }}"><strong>{{ $mission->title }}</strong><span aria-hidden="true">→</span></a>@empty<p>Aucune mission accessible à afficher.</p>@endforelse</section>
</div></x-layouts.member>
