<?php
declare(strict_types=1);
namespace Tests\Feature;
use App\Application\Projects\ProjectConfiguration; use App\Application\Projects\ProjectService; use App\Application\Zumra\ZumraGroupService; use App\Models\PortalAdministrator; use App\Models\PortalSetting; use App\Models\Project; use App\Models\ProjectEvent; use App\Models\ZumraCharter; use App\Models\ZumraGroupMembership; use App\Models\ZumraProgramMembership; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Http; use Tests\TestCase;
final class ProjectTest extends TestCase
{
 use RefreshDatabase;
 public function test_only_an_active_program_member_can_propose_a_project():void{$this->expectException(\Symfony\Component\HttpKernel\Exception\HttpException::class);app(ProjectService::class)->create('IDN-NO',$this->payload(),(new ProjectConfiguration)->defaults());}
 public function test_a_person_creates_an_independent_structured_project():void{$this->member('IDN-OWNER');$p=app(ProjectService::class)->create('IDN-OWNER',$this->payload(),(new ProjectConfiguration)->defaults());self::assertSame(Project::STATUS_PROPOSED,$p->status);self::assertSame('IDEA',$p->maturity);self::assertCount(2,$p->objectives);self::assertCount(3,$p->milestones);self::assertSame('PROJECT_PROPOSED',ProjectEvent::query()->sole()->event);}
 public function test_group_member_proposes_but_leader_adopts():void{$this->member('IDN-LEADER');$this->member('IDN-MEMBER');$g=$this->group('IDN-LEADER');ZumraGroupMembership::query()->create(['zumra_group_id'=>$g->id,'core_identity_reference'=>'IDN-MEMBER','status'=>'ACTIVE','entry_mode'=>'REQUEST','initiated_by_core_reference'=>'IDN-MEMBER','joined_at'=>now()]);$s=app(ProjectService::class);$p=$s->create('IDN-MEMBER',$this->payload(['owner_type'=>'GROUP','group_reference'=>$g->public_reference,'property_regime'=>'ZUMRA_COLLECTIVE']),(new ProjectConfiguration)->defaults());self::assertSame('PROPOSED',$p->status);$s->transition($p,'IDN-LEADER','ADOPTED');self::assertSame('ADOPTED',$p->refresh()->status);}
 public function test_project_visibility_is_identity_scoped():void{$this->member('IDN-ONE');$s=app(ProjectService::class);$private=$s->create('IDN-ONE',$this->payload(['visibility'=>'PRIVATE']),(new ProjectConfiguration)->defaults());$public=$s->create('IDN-ONE',$this->payload(['name'=>'Projet public distinct','visibility'=>'PUBLIC']),(new ProjectConfiguration)->defaults());self::assertFalse($s->canView($private,'IDN-TWO'));self::assertTrue($s->canView($public,'IDN-TWO'));}
 public function test_project_progress_is_traced_without_creating_finance():void{$this->member('IDN-OWNER');$s=app(ProjectService::class);$p=$s->create('IDN-OWNER',$this->payload(),(new ProjectConfiguration)->defaults());$s->transition($p,'IDN-OWNER','IN_PROGRESS','EXPLORATION');$s->transition($p->refresh(),'IDN-OWNER','COMPLETED','ACTIVITY');self::assertSame('COMPLETED',$p->refresh()->status);self::assertSame('ACTIVITY',$p->maturity);self::assertSame(3,ProjectEvent::query()->count());self::assertFalse(\Illuminate\Support\Facades\Schema::hasTable('dg_project_payments'));}
 public function test_admin_configures_domains_and_limits():void{PortalAdministrator::query()->create(['core_identity_reference'=>'IDN-ADMIN']);$this->signIn('IDN-ADMIN');$this->put('/administration/projets',['directory_title'=>'Projets utiles','directory_intro'=>'Des projets administrables sans inventer leur valeur.','creation_title'=>'Proposer','domain_codes'=>['DIGITAL','ENERGY'],'domain_labels'=>['Numérique','Énergie'],'max_active_personal_projects'=>9,'max_active_group_projects'=>25,'directory_page_size'=>18])->assertRedirect();$v=PortalSetting::query()->findOrFail(ProjectConfiguration::KEY);self::assertSame('Énergie',$v->value['domains']['ENERGY']);self::assertSame('IDN-ADMIN',$v->updated_by_core_reference);}
 private function payload(array $x=[]):array{return array_replace(['owner_type'=>'PERSON','group_reference'=>null,'source_need_reference'=>null,'name'=>'Atelier numérique communautaire','summary'=>'Créer un espace pratique où des jeunes peuvent apprendre ensemble et produire des services numériques utiles.','problem'=>'Des jeunes motivés disposent de peu de cadres pratiques pour apprendre, expérimenter et transformer leurs acquis en activités utiles.','proposed_solution'=>'Mettre en place un atelier progressif avec transmission entre pairs, exercices réels et accompagnement vers des premiers services.','beneficiaries'=>'Jeunes débutants et personnes en reconversion dans la commune.','domain'=>'DIGITAL','participation_mode'=>'HYBRID','location'=>'Abidjan','objectives'=>"Former une première équipe\nProduire trois services pilotes",'required_capabilities'=>"Formation numérique\nGestion de projet",'required_resources'=>"Ordinateurs\nConnexion internet",'risks'=>"Disponibilité irrégulière\nAccès au matériel",'milestones'=>"Constituer l’équipe\nPréparer le lieu\nLancer le pilote",'property_regime'=>'PERSONAL_SUPPORTED','visibility'=>'PUBLIC'],$x);}
 private function member(string $id):void{$body=str_repeat('Respect et transmission. ',5);$charter=ZumraCharter::query()->firstOrCreate(['version'=>'2026.1'],['title'=>'Charte ZUMRA','body'=>$body,'content_hash'=>hash('sha256',$body),'status'=>ZumraCharter::STATUS_PUBLISHED,'published_at'=>now()]);ZumraProgramMembership::query()->create(['core_identity_reference'=>$id,'status'=>ZumraProgramMembership::STATUS_ACTIVE,'accepted_charter_id'=>$charter->id,'accepted_charter_version'=>$charter->version,'accepted_charter_hash'=>$charter->content_hash,'charter_accepted_at'=>now(),'submitted_at'=>now(),'activated_at'=>now()]);}
 private function group(string $id){return app(ZumraGroupService::class)->create($id,['name'=>'ZUMRA projets','domain'=>'Numérique','founding_objective'=>'Réunir des personnes afin de structurer et réaliser ensemble des projets utiles et responsables.','participation_mode'=>'HYBRID','internal_charter'=>'Respect, transmission, hiérarchie responsable, consentement et décisions conformes à la doctrine commune.','assume_primary_lead'=>true]);}
 private function signIn(string $r):void{Http::fake(['core.test/api/v1/sessions'=>Http::response(['jeton'=>'bearer-'.$r,'entite'=>$r,'assurance'=>'AS1','expire_le'=>'2026-08-16T23:59:00+00:00'],201),'core.test/api/v1/identites/*'=>Http::response(['reference'=>$r,'type'=>'personne','libelle'=>'Membre DG Afrique','etat'=>'ACTIF','source'=>'CORE','regime'=>'INSCRIT_AU_REGISTRE']),'core.test/api/v1/sessions/current'=>Http::response(['entite'=>$r,'assurance'=>'AS1','expire_le'=>'2026-08-16T23:59:00+00:00'])]);$this->post('/connexion',['identifier'=>$r,'secret'=>'secret'])->assertRedirect('/espace');}
}
