<?php

declare(strict_types=1);
namespace App\Application\ProjectBrain;
use App\Application\Projects\ProjectAuthority; use App\Application\Projects\ProjectConfiguration; use App\Application\Projects\ProjectService; use App\Models\Project; use App\Models\ProjectBrainConversation; use App\Models\ProjectBrainIntent; use App\Models\ProjectBrainMessage; use App\Models\ZumraGroup; use Illuminate\Support\Facades\DB;
/**
 * PROJET-ZUMRA-INVARIANT-001 — le Cerveau converge vers le même invariant que le parcours
 * déterministe : aucun Projet ne naît sans ZUMRA. L'ancrage (context['zumra_group_reference'])
 * reste strictement une décision humaine, jamais gérée par l'IA conversationnelle (project_state,
 * mergeBrainContext()) : ready()/contentReady() sont volontairement distincts pour que l'interface
 * puisse expliquer « le Cerveau a fini, il ne manque que votre choix de ZUMRA » plutôt que de
 * réduire un blocage doctrinal à un simple « pas encore prêt ».
 */
final class ProjectBrainProjectBirthService
{
 public function __construct(private readonly ProjectService $projects,private readonly ProjectConfiguration $configuration,private readonly ProjectAuthority $authority){}
 public function candidate(ProjectBrainIntent $intent):array{$state=is_array($intent->context['project_state']??null)?$intent->context['project_state']:[];$list=static fn(string $key):string=>implode("\n",array_values(array_filter(array_map('strval',is_array($state[$key]??null)?$state[$key]:[]))));$beneficiaries=is_array($state['beneficiaries']??null)?implode(', ',$state['beneficiaries']):(string)($state['beneficiaries']??'');$mode=mb_strtolower((string)($state['mode']??''));$participation=str_contains($mode,'hybrid')||str_contains($mode,'hybride')?'HYBRID':(str_contains($mode,'digital')||str_contains($mode,'ligne')||str_contains($mode,'numérique')?'DIGITAL':'PHYSICAL');return ['owner_type'=>Project::OWNER_PERSON,'group_reference'=>null,'zumra_group_reference'=>$this->zumraGroupReference($intent),'source_need_reference'=>null,'name'=>trim((string)($state['name']??'')),'summary'=>trim((string)($state['summary']??'')),'problem'=>trim((string)($state['problem']??'')),'proposed_solution'=>trim((string)($state['proposed_solution']??'')),'beneficiaries'=>trim($beneficiaries),'domain'=>$this->domain((string)($state['activity']??'')),'participation_mode'=>$participation,'location'=>trim((string)($state['location']??''))?:null,'objectives'=>$list('objectives')?:trim((string)($state['goal']??'')),'required_capabilities'=>$list('required_capabilities'),'required_resources'=>$list('required_resources'),'risks'=>$list('risks'),'milestones'=>$list('milestones'),'property_regime'=>'PERSONAL_SUPPORTED','visibility'=>Project::VISIBILITY_PRIVATE];}
 /** L'IA a-t-elle réuni assez d'éléments narratifs ? Ne dit rien de la ZUMRA, décision humaine distincte. */
 public function contentReady(ProjectBrainIntent $intent):bool{$state=$intent->context['project_state']??[];if(!is_array($state)||($state['ready_for_confirmation']??false)!==true)return false;$c=$this->candidate($intent);return mb_strlen($c['name'])>=5&&mb_strlen($c['summary'])>=40&&mb_strlen($c['problem'])>=40&&mb_strlen($c['proposed_solution'])>=40&&mb_strlen($c['beneficiaries'])>=20&&mb_strlen($c['objectives'])>=5&&mb_strlen($c['milestones'])>=5;}
 /** Prêt à confirmer réellement : contenu structuré ET ZUMRA d'ancrage choisie par la personne. */
 public function ready(ProjectBrainIntent $intent):bool{return $this->contentReady($intent)&&$this->zumraGroup($intent)!==null;}
 /** ZUMRA choisie et valide (membre actif) — jamais devinée, jamais créée automatiquement. */
 public function zumraGroup(ProjectBrainIntent $intent):?ZumraGroup{$reference=$this->zumraGroupReference($intent);if($reference===null)return null;$group=ZumraGroup::query()->where('public_reference',$reference)->first();return $group&&$this->authority->isActiveGroupMember($group->id,$intent->actor_core_reference)?$group:null;}
 private function zumraGroupReference(ProjectBrainIntent $intent):?string{$reference=trim((string)($intent->context['zumra_group_reference']??''));return $reference===''?null:$reference;}
 public function confirm(ProjectBrainIntent $intent,string $actor):Project{abort_unless($intent->actor_core_reference===$actor,404);abort_if($intent->status==='CREATED',409,'Ce projet a déjà été créé.');abort_unless($this->ready($intent),422,'Le Cerveau doit encore clarifier quelques éléments avant la création — y compris la ZUMRA dans laquelle ce projet va grandir.');return DB::transaction(function()use($intent,$actor):Project{$project=$this->projects->create($actor,$this->candidate($intent),$this->configuration->get());$conversation=ProjectBrainConversation::query()->firstOrCreate(['project_id'=>$project->id,'actor_core_reference'=>$actor],['title'=>'Cerveau — '.$project->name]);foreach($intent->messages??[] as $message){$role=($message['role']??'')==='user'?ProjectBrainMessage::ROLE_USER:ProjectBrainMessage::ROLE_ASSISTANT;ProjectBrainMessage::query()->create(['conversation_id'=>$conversation->id,'role'=>$role,'content'=>(string)($message['content']??''),'meta'=>['source'=>'PROJECT_ZERO','intent_id'=>$intent->id]]);}ProjectBrainMessage::query()->create(['conversation_id'=>$conversation->id,'role'=>ProjectBrainMessage::ROLE_SYSTEM,'content'=>'Le Projet Zéro a été confirmé et créé dans le Core. La conversation continue comme mémoire permanente du projet.','meta'=>['project_reference'=>$project->public_reference]]);$context=$intent->context??[];$context['canonical_project_reference']=$project->public_reference;$intent->update(['status'=>'CREATED','context'=>$context]);return $project;});}
 private function domain(string $activity):string{$a=mb_strtolower($activity);$map=['DIGITAL'=>['informat','numéri','digital','logiciel','web','ordinateur'],'EDUCATION'=>['éduc','formation','école','apprentissage'],'HEALTH'=>['santé','médic'],'AGRICULTURE'=>['agric','élevage'],'CRAFT'=>['artisan'],'SOCIAL'=>['social'],'CULTURE'=>['culture']];$allowed=array_keys($this->configuration->get()['domains']??[]);foreach($map as $domain=>$words)if(in_array($domain,$allowed,true))foreach($words as $word)if(str_contains($a,$word))return $domain;return in_array('OTHER',$allowed,true)?'OTHER':(string)($allowed[0]??'OTHER');}
}
