<?php
declare(strict_types=1);
namespace App\Http\Controllers;
use App\Application\Missions\MissionContextRegistry; use App\Application\Needs\NeedService; use App\Application\Partnerships\PartnershipService; use App\Application\Projects\ProjectConfiguration; use App\Application\Projects\ProjectDirectoryDemoContent; use App\Application\Projects\ProjectMaturityService; use App\Application\Projects\ProjectService; use App\Application\Projects\ProjectSignalsEngine; use App\Domain\Identity\CoreIdentity; use App\Http\Controllers\Concerns\PresentsPartnerships; use App\Models\Need; use App\Models\Partnership; use App\Models\PersonProfile; use App\Models\PortalAdministrator; use App\Models\Project; use App\Models\ProjectTeamMember; use App\Models\ZumraGroup; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Pagination\LengthAwarePaginator; use Illuminate\Validation\Rule; use Illuminate\View\View;
final class ProjectController
{
    use PresentsPartnerships;

    // UIUX-009B — la création (create/store) vit désormais dans ProjectDraftController, parcours
    // progressif et sauvegardable indépendant du Cerveau. « projects.create » (route publique)
    // pointe vers ce nouveau contrôleur ; index/show/transition/maturity restent ici, inchangés.
    public function index(Request $request,ProjectConfiguration $configuration,ProjectService $service,ProjectDirectoryDemoContent $demoContent):View{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');$settings=$configuration->get();$domainFilter=$request->filled('domain')&&isset($settings['domains'][(string)$request->query('domain')])?(string)$request->query('domain'):null;$query=Project::query()->where('status','!=',Project::STATUS_ARCHIVED)->latest();if($domainFilter!==null)$query->where('domain',$domainFilter);$visible=$query->limit(300)->get()->filter(fn(Project $p)=>$service->canView($p,$identity->reference))->values();$page=max(1,(int)$request->query('page',1));$per=(int)$settings['directory_page_size'];$projects=new LengthAwarePaginator($visible->forPage($page,$per),$visible->count(),$per,$page,['path'=>$request->url(),'query'=>$request->query()]);$demoCards=$demoContent->demoCards($visible,$page,$domainFilter);$groups=ZumraGroup::query()->whereIn('id',$visible->where('owner_type',Project::OWNER_GROUP)->pluck('owner_reference'))->get()->keyBy('id');$manageableProjectIds=$visible->filter(fn(Project $p)=>$service->canDecide($p,$identity->reference))->pluck('id')->all();$isAdministrator=PortalAdministrator::query()->whereKey($identity->reference)->exists();return view('projects.index',compact('identity','projects','groups','manageableProjectIds','isAdministrator','demoCards')+['configuration'=>$settings,'communityStats'=>$demoContent->communityStats()]);}
    public function show(Request $request,Project $project,ProjectConfiguration $configuration,ProjectService $service,NeedService $needs,ProjectSignalsEngine $signalsEngine,PartnershipService $partnerships,MissionContextRegistry $missionContexts):View{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');abort_unless($service->canView($project,$identity->reference),404);$group=$project->owner_type===Project::OWNER_GROUP?ZumraGroup::query()->find($project->owner_reference):null;$maturityHistory=$project->events()->where('event','PROJECT_MATURITY_CHANGED')->orderByDesc('occurred_at')->get();$isAdministrator=PortalAdministrator::query()->whereKey($identity->reference)->exists();$canDecide=$service->canDecide($project,$identity->reference);
        // UIUX-007 — porte visible vers la création de Mission déjà existante (CAP-069), jamais dupliquée : mêmes conditions que le Cerveau.
        $canProposeMission=$missionContexts->for('PROJECT')->canPropose($project,$identity->reference);
        // UIUX-005 — Partenariats réellement associés à ce Projet, filtrés par la même autorité
        // que le service lui-même (PartnershipService::canView()), jamais recalculée en Blade.
        $projectPartnerships=Partnership::query()->where('context_type',Partnership::CONTEXT_PROJECT)->where('context_reference',$project->public_reference)->latest('created_at')->limit(20)->get()->filter(fn(Partnership $p):bool=>$partnerships->canView($p,$identity->reference))->values();
        $presentedPartnerships=$this->presentPartnerships($projectPartnerships,$identity->reference,$partnerships);
        $manageableOrganizations=$this->manageableOrganizations($identity->reference);
        $manageableOrganizationCapabilities=$this->manageableOrganizationCapabilities($identity->reference);
        // CAP-041 : équipe projet — adhésion réelle, distincte du masquage de suggestion géré par ProjectMatchDecision.
        $teamMembers=ProjectTeamMember::query()->where('project_id',$project->id)->where('status',ProjectTeamMember::STATUS_ACTIVE)->get();
        $myTeamMembership=ProjectTeamMember::query()->where('project_id',$project->id)->where('core_identity_reference',$identity->reference)->first();
        $pendingTeamRequests=$canDecide?ProjectTeamMember::query()->where('project_id',$project->id)->where('status',ProjectTeamMember::STATUS_REQUESTED)->oldest('requested_at')->get():collect();
        $teamProfiles=PersonProfile::query()->whereIn('core_identity_reference',$teamMembers->pluck('core_identity_reference')->merge($pendingTeamRequests->pluck('core_identity_reference')))->get()->keyBy('core_identity_reference');
        // CAP-042 : besoins vivants du projet, distincts de l'instantané figé required_capabilities/required_resources.
        $projectNeeds=Need::query()->where('owner_type',Need::OWNER_PROJECT)->where('owner_reference',$project->id)->where('status','!=',Need::STATUS_ARCHIVED)->latest('created_at')->limit(20)->get()->filter(fn(Need $n)=>$needs->canView($n,$identity->reference))->values();
        $canProposeNeed=$myTeamMembership?->status===ProjectTeamMember::STATUS_ACTIVE||$project->initiator_core_reference===$identity->reference||($project->owner_type===Project::OWNER_PERSON&&$project->owner_reference===$identity->reference);
        // CAP-044 : signaux consultatifs uniquement, jamais un score, jamais une écriture sur maturity.
        $maturitySignals=$signalsEngine->forProject($project);
        $accompaniment=$canDecide?$project->accompaniment:null;
        // Fiche V2 (« Activité récente ») : les 6 derniers événements réels du projet, jamais une reconstruction fictive.
        $recentEvents=$project->events()->latest('occurred_at')->limit(6)->get();
        $eventActorProfiles=PersonProfile::query()->whereIn('core_identity_reference',$recentEvents->pluck('actor_core_reference'))->get()->keyBy('core_identity_reference');
        $lastActivityAt=$recentEvents->first()?->occurred_at??$project->created_at;
        $progressSeed=$project->progressionSeed();
        return view('projects.show',compact('identity','project','group','maturityHistory','isAdministrator','teamMembers','myTeamMembership','pendingTeamRequests','teamProfiles','projectNeeds','canProposeNeed','canProposeMission','maturitySignals','accompaniment','recentEvents','eventActorProfiles','lastActivityAt','progressSeed')+['configuration'=>$configuration->get(),'canDecide'=>$canDecide,'maturityStages'=>ProjectMaturityService::STAGES,'projectPartnerships'=>$presentedPartnerships,'manageableOrganizations'=>$manageableOrganizations,'manageableOrganizationCapabilities'=>$manageableOrganizationCapabilities]);}
    public function transition(Request $request,Project $project,ProjectService $service):RedirectResponse{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');$data=$request->validate(['status'=>['required',Rule::in([Project::STATUS_ADOPTED,Project::STATUS_IN_PROGRESS,Project::STATUS_COMPLETED,Project::STATUS_ARCHIVED])]]);$service->transition($project,$identity->reference,$data['status']);return back()->with('status','L’évolution du statut du projet est enregistrée et traçable. La maturité se gère séparément.');}
    public function maturity(Request $request,Project $project,ProjectMaturityService $service):RedirectResponse{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');$data=$request->validate(['maturity'=>['required',Rule::in(array_keys(ProjectMaturityService::STAGES))],'note'=>['nullable','string','max:1200']]);$service->change($project,$identity->reference,$data['maturity'],$data['note']??null);return back()->with('status','Repère de maturité mis à jour. Il ne constitue ni statut juridique ni décision institutionnelle.');}
}
