<?php

declare(strict_types=1);
namespace App\Http\Controllers;
use App\Application\Needs\NeedConfiguration; use App\Application\Needs\NeedService; use App\Application\ProjectBrain\ProjectBrainNeedDraftService; use App\Application\Projects\ProjectService; use App\Domain\Identity\CoreIdentity; use App\Models\Need; use App\Models\PortalAdministrator; use App\Models\Project; use App\Models\ProjectBrainDraft; use App\Models\ProjectBrainMessage; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\View\View;
final class ProjectBrainController {
 public function show(Request $request,Project $project,ProjectService $projects,NeedService $needs,NeedConfiguration $needConfiguration,ProjectBrainNeedDraftService $brain):View { /** @var CoreIdentity $identity */ $identity=$request->attributes->get('dg_identity'); abort_unless($projects->canView($project,$identity->reference),404); $visibleProjects=Project::query()->whereKey($project->id)->get(); $projectNeeds=Need::query()->where('owner_type',Need::OWNER_PROJECT)->where('owner_reference',$project->id)->where('status','!=',Need::STATUS_ARCHIVED)->latest()->limit(20)->get()->filter(fn(Need $n):bool=>$needs->canView($n,$identity->reference))->values(); $conversation=$brain->conversation($project,$identity->reference); $messages=ProjectBrainMessage::query()->where('conversation_id',$conversation->id)->oldest()->limit(60)->get(); $drafts=ProjectBrainDraft::query()->where('conversation_id',$conversation->id)->where('status',ProjectBrainDraft::STATUS_PENDING)->latest()->get()->keyBy('id'); $isAdministrator=PortalAdministrator::query()->whereKey($identity->reference)->exists(); $viewIdentity=['reference'=>$identity->reference,'display_name'=>$identity->label,'label'=>$identity->label]; return view('projects.brain',['identity'=>$viewIdentity,'project'=>$project,'visibleProjects'=>$visibleProjects,'projectNeeds'=>$projectNeeds,'conversation'=>$conversation,'messages'=>$messages,'drafts'=>$drafts,'isAdministrator'=>$isAdministrator,'needConfiguration'=>$needConfiguration->get()]); }
 public function prepareNeed(Request $request,Project $project,ProjectService $projects,ProjectBrainNeedDraftService $brain):RedirectResponse { /** @var CoreIdentity $identity */ $identity=$request->attributes->get('dg_identity'); abort_unless($projects->canView($project,$identity->reference),404); $data=$request->validate(['message'=>['required','string','min:2','max:3000']]); $draft=$brain->prepare($project,$identity->reference,$data['message']); return redirect()->route('projects.brain.show',$project)->with('status',$draft?'Le Cerveau propose une action. Vérifiez-la : rien n’est créé avant votre confirmation.':'Le Cerveau a pris en compte votre message.'); }
 public function confirmNeed(Request $request,Project $project,ProjectBrainDraft $draft,ProjectService $projects,ProjectBrainNeedDraftService $brain):RedirectResponse { /** @var CoreIdentity $identity */ $identity=$request->attributes->get('dg_identity'); abort_unless($projects->canView($project,$identity->reference),404); $need=$brain->confirm($project,$draft,$identity->reference); return redirect()->route('projects.brain.show',$project)->with('status','Besoin créé dans le Core : '.$need->title); }
 public function cancelDraft(Request $request,Project $project,ProjectBrainDraft $draft,ProjectService $projects,ProjectBrainNeedDraftService $brain):RedirectResponse { /** @var CoreIdentity $identity */ $identity=$request->attributes->get('dg_identity'); abort_unless($projects->canView($project,$identity->reference),404); $brain->cancel($project,$draft,$identity->reference); return redirect()->route('projects.brain.show',$project)->with('status','Proposition abandonnée. Aucune mutation métier.'); }
}
