<?php
declare(strict_types=1);
namespace App\Http\Controllers;
use App\Application\Needs\NeedService; use App\Application\Projects\ProjectConfiguration; use App\Application\Projects\ProjectMaturityService; use App\Application\Projects\ProjectService; use App\Application\Projects\ProjectSignalsEngine; use App\Domain\Identity\CoreIdentity; use App\Models\Need; use App\Models\PersonProfile; use App\Models\PortalAdministrator; use App\Models\Project; use App\Models\ProjectTeamMember; use App\Models\ZumraGroup; use App\Models\ZumraGroupMembership; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Pagination\LengthAwarePaginator; use Illuminate\Validation\Rule; use Illuminate\View\View;
final class ProjectController
{
    public function index(Request $request,ProjectConfiguration $configuration,ProjectService $service):View{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');$settings=$configuration->get();$query=Project::query()->where('status','!=',Project::STATUS_ARCHIVED)->latest()->limit(300);if($request->filled('domain')&&isset($settings['domains'][(string)$request->query('domain')]))$query->where('domain',$request->query('domain'));$visible=$query->get()->filter(fn(Project $p)=>$service->canView($p,$identity->reference))->values();$page=max(1,(int)$request->query('page',1));$per=(int)$settings['directory_page_size'];$projects=new LengthAwarePaginator($visible->forPage($page,$per),$visible->count(),$per,$page,['path'=>$request->url(),'query'=>$request->query()]);$groups=ZumraGroup::query()->whereIn('id',$visible->where('owner_type',Project::OWNER_GROUP)->pluck('owner_reference'))->get()->keyBy('id');$manageableProjectIds=$visible->filter(fn(Project $p)=>$service->canDecide($p,$identity->reference))->pluck('id')->all();$isAdministrator=PortalAdministrator::query()->whereKey($identity->reference)->exists();return view('projects.index',compact('identity','projects','groups','manageableProjectIds','isAdministrator')+['configuration'=>$settings]);}
    public function create(Request $request,ProjectConfiguration $configuration):View{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');$groups=ZumraGroup::query()->whereIn('id',ZumraGroupMembership::query()->where('core_identity_reference',$identity->reference)->where('status',ZumraGroupMembership::STATUS_ACTIVE)->pluck('zumra_group_id'))->orderBy('name')->get();$needs=Need::query()->where('owner_type',Need::OWNER_PERSON)->where('owner_reference',$identity->reference)->whereIn('status',[Need::STATUS_OPEN,Need::STATUS_IN_PROGRESS])->orderBy('title')->get();$isAdministrator=PortalAdministrator::query()->whereKey($identity->reference)->exists();return view('projects.create',compact('identity','groups','needs','isAdministrator')+['configuration'=>$configuration->get()]);}
    public function store(Request $request,ProjectConfiguration $configuration,ProjectService $service):RedirectResponse{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');$settings=$configuration->get();$data=$request->validate(['owner_type'=>['required',Rule::in([Project::OWNER_PERSON,Project::OWNER_GROUP])],'group_reference'=>['nullable','uuid','required_if:owner_type,GROUP'],'source_need_reference'=>['nullable','uuid'],'name'=>['required','string','min:5','max:180'],'summary'=>['required','string','min:40','max:1200'],'problem'=>['required','string','min:40','max:2400'],'proposed_solution'=>['required','string','min:40','max:2400'],'beneficiaries'=>['required','string','min:20','max:1200'],'domain'=>['required',Rule::in(array_keys($settings['domains']))],'participation_mode'=>['required',Rule::in(['PHYSICAL','DIGITAL','HYBRID'])],'location'=>['nullable','string','max:160'],'objectives'=>['required','string','min:5','max:2400'],'required_capabilities'=>['nullable','string','max:2400'],'required_resources'=>['nullable','string','max:2400'],'risks'=>['nullable','string','max:2400'],'milestones'=>['required','string','min:5','max:2400'],'property_regime'=>['required',Rule::in(['PERSONAL_SUPPORTED','ZUMRA_COLLECTIVE','PARTNERSHIP','COMMUNITY_INTEREST'])],'visibility'=>['required',Rule::in([Project::VISIBILITY_PRIVATE,Project::VISIBILITY_GROUP,Project::VISIBILITY_PROGRAM,Project::VISIBILITY_PUBLIC])]]);$project=$service->create($identity->reference,$data,$settings);return redirect()->route('projects.show',$project)->with('status',$project->status===Project::STATUS_ADOPTED?'Projet adopté et enregistré. Aucun financement n’est ouvert.':'Proposition enregistrée. Elle conserve son porteur et ne vaut ni adoption ni financement.');}
    public function show(Request $request,Project $project,ProjectConfiguration $configuration,ProjectService $service,NeedService $needs,ProjectSignalsEngine $signalsEngine):View{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');abort_unless($service->canView($project,$identity->reference),404);$group=$project->owner_type===Project::OWNER_GROUP?ZumraGroup::query()->find($project->owner_reference):null;$maturityHistory=$project->events()->where('event','PROJECT_MATURITY_CHANGED')->orderByDesc('occurred_at')->get();$isAdministrator=PortalAdministrator::query()->whereKey($identity->reference)->exists();$canDecide=$service->canDecide($project,$identity->reference);
        // CAP-041 : équipe projet — adhésion réelle, distincte du masquage de suggestion géré par ProjectMatchDecision.
        $teamMembers=ProjectTeamMember::query()->where('project_id',$project->id)->where('status',ProjectTeamMember::STATUS_ACTIVE)->get();
        $myTeamMembership=ProjectTeamMember::query()->where('project_id',$project->id)->where('core_identity_reference',$identity->reference)->first();
        $pendingTeamRequests=$canDecide?ProjectTeamMember::query()->where('project_id',$project->id)->where('status',ProjectTeamMember::STATUS_REQUESTED)->oldest('requested_at')->get():collect();
        $teamProfiles=PersonProfile::query()->whereIn('core_identity_reference',$teamMembers->pluck('core_identity_reference')->merge($pendingTeamRequests->pluck('core_identity_reference')))->get()->keyBy('core_identity_reference');
        // CAP-042 : besoins vivants du projet, distincts de l'instantané figé required_capabilities/required_resources.
        $projectNeeds=Need::query()->where('owner_type',Need::OWNER_PROJECT)->where('owner_reference',$project->id)->where('status','!=',Need::STATUS_ARCHIVED)->latest('created_at')->limit(20)->get()->filter(fn(Need $n)=>$needs->canView($n,$identity->reference))->values();
        $canProposeNeed=$myTeamMembership?->status===ProjectTeamMember::STATUS_ACTIVE||$project->initiator_core_reference===$identity->reference||($project->owner_type===Project::OWNER_PERSON&&$project->owner_reference===$identity->reference);
        // CAP-044 : signaux consultatifs uniquement, jamais un score, jamais une écriture sur maturity.
        $maturitySignals=$signalsEngine->forProject($project);
        return view('projects.show',compact('identity','project','group','maturityHistory','isAdministrator','teamMembers','myTeamMembership','pendingTeamRequests','teamProfiles','projectNeeds','canProposeNeed','maturitySignals')+['configuration'=>$configuration->get(),'canDecide'=>$canDecide,'maturityStages'=>ProjectMaturityService::STAGES]);}
    public function transition(Request $request,Project $project,ProjectService $service):RedirectResponse{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');$data=$request->validate(['status'=>['required',Rule::in([Project::STATUS_ADOPTED,Project::STATUS_IN_PROGRESS,Project::STATUS_COMPLETED,Project::STATUS_ARCHIVED])]]);$service->transition($project,$identity->reference,$data['status']);return back()->with('status','L’évolution du statut du projet est enregistrée et traçable. La maturité se gère séparément.');}
    public function maturity(Request $request,Project $project,ProjectMaturityService $service):RedirectResponse{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');$data=$request->validate(['maturity'=>['required',Rule::in(array_keys(ProjectMaturityService::STAGES))],'note'=>['nullable','string','max:1200']]);$service->change($project,$identity->reference,$data['maturity'],$data['note']??null);return back()->with('status','Repère de maturité mis à jour. Il ne constitue ni statut juridique ni décision institutionnelle.');}
}
