<?php

declare(strict_types=1);
namespace App\Http\Controllers;
use App\Application\Projects\ProjectAuthority; use App\Application\ProjectBrain\ProjectBrainAiProvider; use App\Application\ProjectBrain\ProjectBrainProjectBirthService; use App\Application\Zumra\ZumraGroupConfiguration; use App\Application\Zumra\ZumraGroupService; use App\Domain\Identity\CoreIdentity; use App\Models\PortalAdministrator; use App\Models\ProjectBrainIntent; use App\Models\ZumraGroup; use App\Models\ZumraGroupMembership; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\Log; use Illuminate\Support\Str; use Illuminate\Validation\Rule; use Illuminate\View\View; use Throwable;
final class ProjectBrainStartController
{
    public function create(Request $request):View{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');$isAdministrator=PortalAdministrator::query()->whereKey($identity->reference)->exists();return view('projects.brain-start',compact('identity','isAdministrator'));}
    public function store(Request $request,ProjectBrainAiProvider $brain):RedirectResponse{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');$data=$request->validate(['message'=>['required','string','min:12','max:3000']]);$message=trim($data['message']);$messages=[['role'=>'user','content'=>$message,'at'=>now()->toIso8601String()]];$context=['initial_intent'=>$message];$result=$this->askBrain($brain,$messages,$context);$messages[]=['role'=>'brain','content'=>$result['reply'],'at'=>now()->toIso8601String()];$context=$this->mergeBrainContext($context,$result);$intent=ProjectBrainIntent::query()->create(['actor_core_reference'=>$identity->reference,'title'=>Str::limit($message,72,'…'),'messages'=>$messages,'context'=>$context,'status'=>'DRAFT']);return redirect()->route('projects.brain.start.show',$intent);}
    public function show(Request $request,ProjectBrainIntent $intent,ProjectBrainProjectBirthService $birth):View{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');abort_unless($intent->actor_core_reference===$identity->reference,404);$isAdministrator=PortalAdministrator::query()->whereKey($identity->reference)->exists();$candidate=$birth->candidate($intent);$contentReady=$birth->contentReady($intent);$readyForConfirmation=$birth->ready($intent);$groups=$this->activeGroups($identity->reference);return view('projects.brain-start',compact('identity','isAdministrator','intent','candidate','contentReady','readyForConfirmation','groups'));}
    public function reply(Request $request,ProjectBrainIntent $intent,ProjectBrainAiProvider $brain):RedirectResponse{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');abort_unless($intent->actor_core_reference===$identity->reference,404);abort_if($intent->status==='CREATED',409);$data=$request->validate(['message'=>['required','string','min:2','max:3000']]);$messages=$intent->messages??[];$messages[]=['role'=>'user','content'=>trim($data['message']),'at'=>now()->toIso8601String()];$context=$intent->context??[];$result=$this->askBrain($brain,$messages,$context);$messages[]=['role'=>'brain','content'=>$result['reply'],'at'=>now()->toIso8601String()];$context=$this->mergeBrainContext($context,$result);$intent->update(['messages'=>$messages,'context'=>$context]);return redirect()->route('projects.brain.start.show',$intent);}
    public function confirm(Request $request,ProjectBrainIntent $intent,ProjectBrainProjectBirthService $birth):RedirectResponse{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');$project=$birth->confirm($intent,$identity->reference);return redirect()->route('projects.brain.show',$project)->with('status','Projet créé après votre confirmation. La conversation devient maintenant le Cerveau permanent du projet.');}

    /**
     * PROJET-ZUMRA-INVARIANT-001 — choix humain explicite d'une ZUMRA déjà rejointe, jamais
     * suggéré ni décidé par l'IA (context['zumra_group_reference'] vit hors de project_state).
     */
    public function selectZumra(Request $request,ProjectBrainIntent $intent,ProjectAuthority $authority):RedirectResponse{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');abort_unless($intent->actor_core_reference===$identity->reference,404);abort_if($intent->status==='CREATED',409);$data=$request->validate(['zumra_group_reference'=>['required','string']]);$group=ZumraGroup::query()->where('public_reference',$data['zumra_group_reference'])->first();abort_unless($group&&$authority->isActiveGroupMember($group->id,$identity->reference),422,'Choisissez une ZUMRA dont vous êtes membre actif.');$context=$intent->context??[];$context['zumra_group_reference']=$group->public_reference;$intent->update(['context'=>$context]);return redirect()->route('projects.brain.start.show',$intent);}

    /** Même mécanisme que le parcours déterministe (ProjectDraftController) : jamais silencieux, jamais de rôle imposé. */
    public function newZumra(Request $request,ProjectBrainIntent $intent):View{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');abort_unless($intent->actor_core_reference===$identity->reference,404);abort_if($intent->status==='CREATED',409);$isAdministrator=PortalAdministrator::query()->whereKey($identity->reference)->exists();return view('projects.brain-zumra-nouvelle',compact('identity','isAdministrator','intent'));}

    public function storeZumra(Request $request,ProjectBrainIntent $intent,ZumraGroupService $groups,ZumraGroupConfiguration $configuration):RedirectResponse{/** @var CoreIdentity $identity */$identity=$request->attributes->get('dg_identity');abort_unless($intent->actor_core_reference===$identity->reference,404);abort_if($intent->status==='CREATED',409);$data=$request->validate(['name'=>['required','string','min:3','max:140',Rule::unique('dg_zumra_groups','name')],'domain'=>['required','string','min:3','max:140'],'founding_objective'=>['required','string','min:40','max:1800'],'participation_mode'=>['required',Rule::in(['PHYSICAL','DIGITAL','HYBRID'])],'internal_charter'=>['required','string','min:80','max:6000']]);$data['assume_primary_lead']=true;$group=$groups->create($identity->reference,$data,(int)$configuration->get()['max_simultaneous_founder_roles']);$context=$intent->context??[];$context['zumra_group_reference']=$group->public_reference;$intent->update(['context'=>$context]);return redirect()->route('projects.brain.start.show',$intent)->with('status','Votre ZUMRA « '.$group->name.' » est créée.');}

    private function activeGroups(string $actor):\Illuminate\Support\Collection{return ZumraGroup::query()->whereIn('id',ZumraGroupMembership::query()->where('core_identity_reference',$actor)->where('status',ZumraGroupMembership::STATUS_ACTIVE)->pluck('zumra_group_id'))->orderBy('name')->get();}
    private function askBrain(ProjectBrainAiProvider $brain,array $messages,array $context):array{try{return $brain->respond($messages,$context['project_state']??[]);}catch(Throwable $exception){Log::warning('Project Brain AI unavailable; deterministic fallback used.',['exception'=>$exception::class,'message'=>$exception->getMessage()]);return ['reply'=>'Je garde bien votre message. Mon intelligence d’analyse est momentanément indisponible, mais votre brouillon reste sauvegardé.','project_state'=>is_array($context['project_state']??null)?$context['project_state']:[],'suggested_next_action'=>null,'confidence'=>null];}}
    private function mergeBrainContext(array $context,array $result):array{$context['project_state']=$result['project_state'];$context['suggested_next_action']=$result['suggested_next_action'];$context['ai_confidence']=$result['confidence'];$context['ai_provider']='deepseek';$context['ai_model']=(string)config('services.deepseek.model','deepseek-v4-flash');return $context;}
}
